name: Wiki Sync

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: JoeIzzard/ghaction-wiki-sync@v1
      with:
        username: LinkStackOrg
        access_token: "{{ secrets.GH_TOKEN }}"
        wiki_folder: "docs"
        commit_message: "Update Wiki"
        commit_username: "JulianPrieber"
        commit_email: "JulianPrieber@users.noreply.github.com"